default: true

line-length: false

single-title:
  front_matter_title: title

no-trailing-punctuation: false
no-inline-html: false
no-bare-urls: false
no-emphasis-as-heading: false
fenced-code-language: false
